### ISSUE TITLE
macOS Sierra sed command different behaviour

### ISSUE THREAD

**Issue by jeanchlopez** [red-hat-storage/ocs-training#68] opened 2019-10-29 15:40 UTC
**Do you need more detailed steps on an existing section? Please describe.**
When running the lab content from a macOS 10.12 Sierra laptop sed does not behave as expected if we follow the instructions

**Describe what you would like to see**
Content currently shows the following
`sed -i "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1a.yaml`
`sed -i "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1b.yaml`
`sed -i "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1c.yaml`

**Describe alternatives you've considered**
`sed -i "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1a.yaml`
`sed -i "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1b.yaml`
`sed -i "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1c.yaml`

If using macOS Sierra 10.12 series use the following set of commands:
`sed -i -e "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1a.yaml`
`sed -i -e "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1b.yam`l
`sed -i -e "s/cluster-28cf-t22gs/$CLUSTERID/g" cluster-workerocs-us-east-1c.yaml`

**Additional context**
N/A

**Comment by mulbc** [comment] 2019-10-29 16:06
Isn't that a duplicate of https://github.com/red-hat-storage/ocs-training/issues/61 ??

**Closed** 2019-10-29 16:31 UTC
Labels: enhancement, need review
