### ISSUE TITLE
adding more OCP worker nodes for OCS 4.2 resources will fail if we choose the workshop with APAC region

### ISSUE THREAD

**Issue by chidambaramm** [red-hat-storage/ocs-training#116] opened 2019-11-24 14:54 UTC
**Describe the bug**

Reference LAB Guide: https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc

Adding more OCP worker nodes for OCS 4.2 resources will fail if we choose to deploy the Openshift 4.2 workshop with APAC region

**Section in which you face the issue**
Provide the Section title or a link to the section

When executing this command to create new worker nodes for the purpose of OCS 4.2
curl -s https://raw.githubusercontent.com/red-hat-storage/ocs-training/master/ocp4ocs4/cluster-workerocs.yaml | sed "s/CLUSTERID/$CLUSTERID/g" | oc apply -f -

cluster-workerocs.yaml is pointing to region "us-east".  Hence the command "watch oc get machinesets -n openshift-machine-api" will never show the newly created worker nodes are ready.  

placement:
            availabilityZone: us-east-1a
            region: us-east-1
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - CLUSTERID-worker-sg

**To Reproduce**
RHPDS -> Catalog -> workshops -> openshift 4.2 workshop
Order and choose Region as "APAC" instead of default "North America"

Then Continue the lab as per the document "https://github.com/red-hat-storage/ocs-training/blob/master/ocp4ocs4/ocs4.adoc"

**Expected behavior**

When executing this command: "curl -s https://raw.githubusercontent.com/red-hat-storage/ocs-training/master/ocp4ocs4/cluster-workerocs.yaml | sed "s/CLUSTERID/$CLUSTERID/g" | oc apply -f -" 
You will see the additional worker nodes created. But it will not come to ready state when check the status of the new worker nodes with this command:

"watch oc get machinesets -n openshift-machine-api"

and if the workshop is to deploy and learn OCS 4.2, without these additional worker nodes, you can not proceed further in this workshop. 

Solution:
Option 1. Order the RHPDS Openshift 4.2 workshop with Region : North America, since the  Yaml file here "https://raw.githubusercontent.com/red-hat-storage/ocs-training/master/ocp4ocs4/cluster-workerocs.yaml"  is pointing to AWS US-EAST region.  

> Tested working

Option 2. Edit the Yaml file to reflect the correct AWS region 

> Not tested

**Screenshots**

**Environment**
 - OS: [e.g. OSX, Fedora,...]

**Did you use OCP deployed by the RHPDS workshop?**
Yes/No

YES

**Additional context**

**Comment by mulbc** [comment] 2019-11-25 16:01
Duplicate of #76?

**Closed** 2019-12-02 13:42 UTC
Labels: bug
